### ISSUE TITLE
"'NoneType' object has no attribute 'encode'" error if request `body` key is null

### ISSUE THREAD

**Issue by npvisual** [fondat/fondat-aws#4]
While testing with a simple "API Gateway Event" JSON that represented a "GET" request with a null value for the `body` key, we got the following error : 

```json
{"errorMessage": "'NoneType' object has no attribute 'encode'", "errorType": "AttributeError", "stackTrace": ["  File \"/opt/venv/lib/python3.9/site-packages/fondat/aws/lambda_.py\", line 57, in function\n    return asyncio.run(coro)\n", "  File \"/usr/local/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n", "  File \"/usr/local/lib/python3.9/asyncio/base_events.py\", line 642, in run_until_complete\n    return future.result()\n", "  File \"/opt/venv/lib/python3.9/site-packages/fondat/aws/lambda_.py\", line 37, in coroutine\n    b64decode(event[\"body\"]) if event[\"isBase64Encoded\"] else event[\"body\"].encode()\n"]}
```

The following line seems to be the issue since there is no check on whether `body` is null before calling the encoding / decoding methods.

https://github.com/fondat/fondat-aws/blob/c78e54a9f3011cbda46d6fbde02b808aec19b562/fondat/aws/lambda_.py#L37

**Comment by npvisual** [comment]
FYI. Was testing with the AWS Console Test tool and got another error. For the "API Gateway AWS Proxy" (which I assume is what we'll be using) the JSON provided triggers an error due to the different content of `requestContext` : 

```json
{
  "body": "eyJ0ZXN0IjoiYm9keSJ9",
  "resource": "/{proxy+}",
  "path": "/path/to/resource",
  "httpMethod": "POST",
  "isBase64Encoded": true,
  "queryStringParameters": {
    "foo": "bar"
  },
  "multiValueQueryStringParameters": {
    "foo": [
      "bar"
    ]
  },
  "pathParameters": {
    "proxy": "/path/to/resource"
  },
  "stageVariables": {
    "baz": "qux"
  },
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, sdch",
    "Accept-Language": "en-US,en;q=0.8",
    "Cache-Control": "max-age=0",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    "Host": "1234567890.execute-api.us-east-2.amazonaws.com",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Custom User Agent String",
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "multiValueHeaders": {
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    ],
    "Accept-Encoding": [
      "gzip, deflate, sdch"
    ],
    "Accept-Language": [
      "en-US,en;q=0.8"
    ],
    "Cache-Control": [
      "max-age=0"
    ],
    "CloudFront-Forwarded-Proto": [
      "https"
    ],
    "CloudFront-Is-Desktop-Viewer": [
      "true"
    ],
    "CloudFront-Is-Mobile-Viewer": [
      "false"
    ],
    "CloudFront-Is-SmartTV-Viewer": [
      "false"
    ],
    "CloudFront-Is-Tablet-Viewer": [
      "false"
    ],
    "CloudFront-Viewer-Country": [
      "US"
    ],
    "Host": [
      "0123456789.execute-api.us-east-2.amazonaws.com"
    ],
    "Upgrade-Insecure-Requests": [
      "1"
    ],
    "User-Agent": [
      "Custom User Agent String"
    ],
    "Via": [
      "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)"
    ],
    "X-Amz-Cf-Id": [
      "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA=="
    ],
    "X-Forwarded-For": [
      "127.0.0.1, 127.0.0.2"
    ],
    "X-Forwarded-Port": [
      "443"
    ],
    "X-Forwarded-Proto": [
      "https"
    ]
  },
  "requestContext": {
    "accountId": "123456789012",
    "resourceId": "123456",
    "stage": "prod",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "requestTime": "09/Apr/2015:12:34:56 +0000",
    "requestTimeEpoch": 1428582896000,
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": null,
      "cognitoIdentityId": null,
      "caller": null,
      "accessKey": null,
      "sourceIp": "127.0.0.1",
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": null,
      "userAgent": "Custom User Agent String",
      "user": null
    },
    "path": "/prod/path/to/resource",
    "resourcePath": "/{proxy+}",
    "httpMethod": "POST",                                             <------------- should we use this instead ?
    "apiId": "1234567890",
    "protocol": "HTTP/1.1"
  }
}
```

as opposed to the following (used for initial testing) where the `http` values are broken down into an object : 

```json
        "requestContext": {
            "authorizer": {},
            "domainName": "localhost",
            "domainPrefix": "",
            "http": {
                "method": "GET",
                "path": "/v1/session/info",
                "protocol": "HTTP/1.1",
                "sourceIp": "127.0.0.1",
                "userAgent": "test"
            },
```

Here's the relevant part of the error message : 

```
  File "/opt/venv/lib/python3.9/site-packages/fondat/aws/lambda_.py", line 23, in coroutine
    http = event["requestContext"]["http"]
```

**Comment by npvisual** [comment]
One more issue : the `request` object is called with the `header` attribute. It should be `headers` I believe.

```
[ERROR] AttributeError: 'Request' object has no attribute 'header'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/fondat/aws/lambda_.py", line 57, in function
    return asyncio.run(coro)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.9/site-packages/fondat/aws/lambda_.py", line 31, in coroutine
    request.header[key] = value
```

**Comment by npvisual** [comment]
The test JSON also didn't have any parameter `cookies`. So the following triggered an error : 

```
            for cookie in event["cookies"]:
                request.cookies.load(cookie)
```

**Comment by npvisual** [comment]
Good link to define the JSON blob passed down from the API Gateway : 
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

Seems like the 2.0 version is more in line with what's currently defined in the `lambda_` handler.
